name: workflow-ci-env
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - mlflow==2.19.0
      - matplotlib
      - seaborn
      - openpyxl