# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_KDzjzbOuYJJD8daY5q3M_czExSI4YU

#Melatih model Machine Learning (RandomForestClassifier) menggunakan dataset preprocessing, log ke MLflow Tracking UI lokal
"""

!pip install --quiet mlflow==2.19.0 scikit-learn==1.5.2 pandas pyngrok

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.metrics import accuracy_score, roc_auc_score
import mlflow, mlflow.sklearn, os, shutil
from pyngrok import ngrok
from google.colab import files

# Load dataset
import pandas as pd
df = pd.read_csv("diabetes_clean.csv")
X = df.drop("Outcome", axis=1)
y = df["Outcome"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Siapkan MLflow
mlflow.sklearn.autolog()
os.makedirs("mlruns", exist_ok=True)
mlflow.set_tracking_uri("file://" + os.path.abspath("mlruns"))

# Train model
mlflow.set_experiment("RandomForest Model")
with mlflow.start_run():
    model = RandomForestClassifier(random_state=42)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_pred)

    # Log metric manual
    mlflow.log_metric("accuracy_manual", acc)
    mlflow.log_metric("roc_auc_manual", auc)

    # Log model profesional
    mlflow.sklearn.log_model(
        sk_model=model,
        artifact_path="model_rf",
        input_example=X_train.iloc[:5],
        signature=mlflow.models.infer_signature(X_train, model.predict(X_train))
    )

print(f"Training selesai. Accuracy: {acc:.4f}, ROC AUC: {auc:.4f}")

!ngrok authtoken 3CCiAU7etiXKGw1cYAkcr6Nzcy7_Z4Fzsxhj6bnLixCymHvb

get_ipython().system_raw("mlflow ui --port 5000 &")
public_url = ngrok.connect(5000)
print("🔗 MLflow Tracking UI:", public_url)

# Download artefak model
experiment_id = mlflow.get_experiment_by_name("RandomForest Model").experiment_id
run_id = os.listdir(f"mlruns/{experiment_id}")[0]
shutil.make_archive("model_rf_artifact", 'zip', f"mlruns/{experiment_id}/{run_id}/artifacts/model_rf")
files.download("model_rf_artifact.zip")
print("Artefak model siap diunduh")